CREATE TABLE role_resource(
  id INT(10) PRIMARY KEY AUTO_INCREMENT,
  role_id INT(10) NOT NULL COMMENT '角色id',
  user_id INT(10) NOT NULL COMMENT '用户id',
  resource_id INT(10) NOT NULL COMMENT '觉得配置id',
  create_time TIMESTAMP NULL COMMENT '创建时间',
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  flag INT (4) DEFAULT 0 COMMENT ''
)ENGINE = InnoDB DEFAULT CHARSET=utf8 COMMENT '角色用户配置关联表'