CREATE TABLE role(
  id INT(10) PRIMARY KEY AUTO_INCREMENT,
  role_name VARCHAR(10) NOT NULL COMMENT '角色名',
  status INT (4) DEFAULT 1 COMMENT '状态0停用，1启用，默认启用',
  type INT (4) DEFAULT 0 COMMENT '类型0普通用户，1超级管理员，默认普通',
  create_time TIMESTAMP NULL COMMENT '创建时间',
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  flag INT (4) DEFAULT 0 COMMENT ''
)ENGINE = InnoDB DEFAULT CHARSET=utf8 COMMENT '角色表'