CREATE TABLE theme_user(
  id INT(10) PRIMARY KEY AUTO_INCREMENT,
  user_id INT(10) NOT NULL COMMENT '用户id',
  theme_id INT(10) NOT NULL COMMENT '皮肤id',
  type INT (4) DEFAULT 0 COMMENT '类型',
  status INT (4) DEFAULT 1 COMMENT '状态0停用，1启用，默认启用',
  create_time TIMESTAMP NULL COMMENT '创建时间',
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  flag INT (4) DEFAULT 0 COMMENT ''
)ENGINE = InnoDB DEFAULT CHARSET=utf8 COMMENT '皮肤用户关联表'
